FROM jrei/systemd-ubuntu:20.04

RUN apt-get update

RUN apt-get install -y net-tools
RUN apt-get install -y tcpdump
RUN apt-get install -y iputils-ping
RUN apt-get install -y vim
RUN apt-get install -y nginx


RUN apt-get install -y python3 python3-venv libaugeas0
RUN python3 -m venv /opt/certbot/
RUN /opt/certbot/bin/pip install --upgrade pip
RUN /opt/certbot/bin/pip install certbot certbot-nginx
RUN ln -s /opt/certbot/bin/certbot /usr/bin/certbot

RUN apt-get install cron
RUN apt-get install -y curl

RUN echo "0 0,12 * * * root /opt/certbot/bin/python -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot renew -q" >> /etc/crontab
RUN echo "0 0,12 * * * root /opt/certbot/bin/pip install --upgrade certbot" >> /etc/crontab

COPY certbot-nginx.ini .
COPY getSsl.sh .


